version: '3.9'

services:
  server:
    build: .
    ports: 
      - "8081:8080"
    depends_on:
      - db
    restart: always

  db:
    image: 'postgres'
    ports:
      - '4444:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '4123'